version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'dtc-de-446723') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'fitbit_dataset') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: external_profile
      - name: external_heartrate
      - name: external_sleep
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg_heartrate_data
      description: placeholderDescription 
      columns:
          - name: Trip_distance 
            description: placeholderDescription 
          - name: Pickup_locationid
            description: placeholderDescription 
            tests:
              - relationships:
                  to: ref('taxi_zone_lookup')
                  field: locationid
                  severity: warn
          - name: dropoff_locationid 
            description: placeholderDescription 
            tests:
              - relationships:
                  to: ref('taxi_zone_lookup')
                  field: locationid
          - name: RateCodeID 
            description: placeholderDescription 

    - name: stg_sleep_data
      description: placeholderDescription 
      columns:
          - name: dateOfSleep
            description: The date the sleep log ended. 
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: warn
          - name: duration 
            description: placeholderDescription 
          - name: pickup_datetime 
            description: placeholderDescription 
          - name: dropoff_datetime 
            description: placeholderDescription 
          - name: Passenger_count 
            description: placeholderDescription 
          - name: Trip_distance 
            description: placeholderDescription 
          - name: Pickup_locationid
            description: placeholderDescription 
            tests:
              - relationships:
                  to: ref('taxi_zone_lookup')
                  field: locationid
                  severity: warn
          - name: dropoff_locationid 
            description: placeholderDescription 
            tests:
              - relationships:
                  to: ref('taxi_zone_lookup')
                  field: locationid
                  severity: warn
          - name: RateCodeID 
            description: placeholderDescription 
          - name: Store_and_fwd_flag 
            description: placeholderDescription 
              This flag indicates whether the trip record was held in vehicle
              memory before sending to the vendor, aka “store and forward,”
              because the vehicle did not have a connection to the server.
                Y= store and forward trip
                N= not a store and forward trip
          - name: Dropoff_longitude 
            description: placeholderDescription 
          - name: Dropoff_latitude 
            description: placeholderDescription 
          - name: Payment_type 
            description: placeholderDescription 
            tests: 
              - accepted_values:
                  values: "{{ var('payment_type_values') }}"
                  severity: warn
                  quote: false
          - name: payment_type_description
            description: placeholderDescription 
          - name: Fare_amount 
            description: placeholderDescription 
          - name: Improvement_surcharge 
            description: placeholderDescription 
          - name: Tip_amount 
            description: placeholderDescription 
          - name: Tolls_amount 
            description: placeholderDescription 
          - name: Total_amount 
            description: 